const DEFAULT={business_name:"GERDEV Business Order",whatsapp:"6281234567890",address:"Indonesia",products:[
{id:1,name:"Paket Basic",category:"Jasa",price:450000,description:"Paket website bisnis untuk kebutuhan dasar.",image:""},
{id:2,name:"Paket Professional",category:"Jasa",price:650000,description:"Website bisnis dengan katalog dan order WhatsApp.",image:""},
{id:3,name:"Paket Business Order",category:"Jasa",price:900000,description:"Website dengan katalog, keranjang, checkout dan admin.",image:""}
]};
function db(){return JSON.parse(localStorage.getItem("gerdev_db")||JSON.stringify(DEFAULT))}
function saveDB(x){localStorage.setItem("gerdev_db",JSON.stringify(x))}
function cart(){return JSON.parse(localStorage.getItem("gerdev_cart")||"[]")}
function saveCart(x){localStorage.setItem("gerdev_cart",JSON.stringify(x));updateCount()}
function rupiah(n){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
function updateCount(){let n=cart().reduce((s,x)=>s+x.qty,0);document.querySelectorAll("#cartCount").forEach(e=>e.textContent=n)}
function card(p){return `<article class="card"><div class="card-img">${p.name}</div><h3>${p.name}</h3><p class="price">${rupiah(p.price)}</p><small>${p.description}</small><a class="btn" href="product.html?id=${p.id}">Lihat Detail</a></article>`}
function renderFeatured(){let d=db();document.getElementById("featured").innerHTML=d.products.map(card).join("");let w=document.getElementById("waBtn");if(w)w.href=`https://wa.me/${d.whatsapp}`;updateCount()}
function renderProducts(){let d=db(),g=document.getElementById("productGrid"),s=document.getElementById("search"),c=document.getElementById("category");[...new Set(d.products.map(x=>x.category))].forEach(x=>c.innerHTML+=`<option>${x}</option>`);function go(){let q=s.value.toLowerCase(),cat=c.value;g.innerHTML=d.products.filter(x=>(!q||x.name.toLowerCase().includes(q))&&(!cat||x.category===cat)).map(card).join("")||"<p>Produk tidak ditemukan.</p>"}s.oninput=go;c.onchange=go;go();updateCount()}
function renderDetail(){let id=+new URLSearchParams(location.search).get("id"),p=db().products.find(x=>x.id===id),d=document.getElementById("detail");if(!p){d.innerHTML="<h1>Produk tidak ditemukan</h1>";return}d.innerHTML=`<div class="detail"><div class="card-img">${p.name}</div><div><p class="eyebrow">${p.category}</p><h1>${p.name}</h1><h2>${rupiah(p.price)}</h2><p class="muted">${p.description}</p><button class="btn" onclick="addToCart(${p.id})">Tambah ke Pesanan</button></div></div>`;updateCount()}
function addToCart(id){let c=cart(),i=c.findIndex(x=>x.id===id);i>=0?c[i].qty++:c.push({id,qty:1});saveCart(c);location.href="cart.html"}
function renderCart(){let d=db(),c=cart(),el=document.getElementById("cart");if(!c.length){el.innerHTML="<p class='muted'>Keranjang masih kosong.</p><a class='btn' href='products.html'>Lihat Katalog</a>";updateCount();return}let total=0;el.innerHTML=c.map(x=>{let p=d.products.find(y=>y.id===x.id),sub=p.price*x.qty;total+=sub;return `<div class="row"><div><b>${p.name}</b><small>${rupiah(p.price)}</small></div><div class="qty"><button onclick="changeQty(${x.id},-1)">−</button> ${x.qty} <button onclick="changeQty(${x.id},1)">+</button></div><strong>${rupiah(sub)}</strong><button class="danger" onclick="removeCart(${x.id})">Hapus</button></div>`}).join("")+`<div class="row"><strong>Total</strong><strong>${rupiah(total)}</strong></div><a class="btn" href="checkout.html">Checkout</a>`;updateCount()}
function changeQty(id,n){let c=cart(),x=c.find(y=>y.id===id);x.qty+=n;if(x.qty<1)c=c.filter(y=>y.id!==id);saveCart(c);renderCart()}
function removeCart(id){saveCart(cart().filter(x=>x.id!==id));renderCart()}
function renderCheckout(){let d=db(),c=cart(),total=0;document.getElementById("checkoutSummary").innerHTML=c.map(x=>{let p=d.products.find(y=>y.id===x.id),s=p.price*x.qty;total+=s;return `<div class="row"><span>${p.name} × ${x.qty}</span><b>${rupiah(s)}</b></div>`}).join("")+`<div class="row"><b>Total</b><b>${rupiah(total)}</b></div>`;document.getElementById("checkoutForm").onsubmit=e=>{e.preventDefault();let order={id:"ORD-"+Date.now(),name:name.value,phone:phone.value,address:address.value,notes:notes.value,items:c,total,status:"BARU",created_at:new Date().toISOString()};let orders=JSON.parse(localStorage.getItem("gerdev_orders")||"[]");orders.push(order);localStorage.setItem("gerdev_orders",JSON.stringify(orders));let lines=c.map(x=>{let p=d.products.find(y=>y.id===x.id);return `• ${p.name} x${x.qty} — ${rupiah(p.price*x.qty)}`}).join("%0A");let msg=`Halo, saya ingin melakukan pesanan.%0A%0AOrder: ${order.id}%0ANama: ${order.name}%0AWhatsApp: ${order.phone}%0A%0A${lines}%0A%0ATotal: ${rupiah(total)}%0ACatatan: ${order.notes||"-"}`;localStorage.removeItem("gerdev_cart");location.href=`https://wa.me/${d.whatsapp}?text=${msg}`}}
updateCount();